export const projects = [
  {
    title: 'Store clothes',
    description: "This project was my first job with real client, is webpage to buy clothes using Whatsapp for checking the orders.",
    image: '/images/portafolio/KOCHANIE.PNG',
    tags: ['React', 'JavaScript', 'SASS'],
    source: 'https://github.com/RafaelRamirez21/Clothing-Store',
    visit: 'https://kochanie-store.netlify.app/',
    id: 0,
  },
  {
    title: 'Challenges',
    description: "This is a landing page with the porpuse of show the JavaScript Challenges that I  did for improve my javascripts, css skills.",
    image: '/images/portafolio/Landing-challenges.PNG',
    tags: ['React', 'JavaScripts', 'CSS'],
    source: 'https://github.com/RafaelRamirez21/Challenges-WebPages',
    visit: 'https://js-css-challenges.netlify.app/',

    id: 1,
  },
  {
    title: 'CRUD angular',
    description: "This was my first mini project with Angular based on API REST that built with nodejs and typescript.",
    image: '/images/portafolio/CRUD-ANGULAR.PNG',
    tags: ['Typescript', 'Angular', 'API Rest', 'MySQL'],
    source: 'https://github.com/RafaelRamirez21/crud-angular-movies',
    visit: 'https://crud-movie.netlify.app/read',
    id: 2,
  },
  {
    title: 'Tributte pages',
    description: "This was my first page I put in my portfolio because I so proud about it and is way to show my progress.",
    image: '/images/portafolio/tributte.PNG',
    tags: ['HTML', 'CSS'],
    source: 'https://github.com/RafaelRamirez21/Tribute-Page',
    visit: 'https://rafaelramirez21.github.io/Tribute-Page/',
    id: 3,
  },

  {
    title: 'Dashboard Mercatodo',
    description: "This was a dashboard for mercatodo that  fetching data from API REST that built with django.",
    image: '/images/portafolio/MERCATODOe.PNG',
    tags: ['React', 'Django', 'python', 'API Rest', 'MySQL'],
    source: 'https://github.com/amendivelso/merca_todo',
    visit: 'https://merca-todo-hazel.vercel.app/',
    id: 4,
  },
  {
    title: 'Criptocurrency Info',
    description: "This project is based on ant design and used Redux for fetching the data from different API REST.",
    image: '/images/portafolio/CRYPTO.PNG',
    tags: ['React', 'ant design', 'API Rest'],
    source: 'https://github.com/RafaelRamirez21/Cryptocurrency-App',
    visit: 'https://crypto-info-ant.netlify.app',
    id: 5,
  },
  {
    title: 'Musical Landing',
    description: "Using vanilla Javascript the objective of this project is consuming a Giphy API and improve css skills.",
    image: '/images/portafolio/musical.png',
    tags: ['JavaScript', 'html', 'Node', 'CSS'],
    source: 'https://github.com/RafaelRamirez21/Web-Audio-API',
    visit: 'https://rafaelramirez21.github.io/Web-Audio-API/',
    id: 6,
  },
  {
    title: 'Todo List',
    description: "Using Rect I made a functional app for save your task.",
    image: '/images/portafolio/TODO-LIST.PNG',
    tags: ['React', 'CSS'],
    source: 'https://github.com/RafaelRamirez21/React-JS-Mini-Project/tree/main/React-ToDo-list',
    visit: 'https://todo-react-red.netlify.app/',
    id: 7,
  },
  {
    title: 'Video game pages',
    description: "Using Angular for fetching from API about games.",
    image: '/images/portafolio/game.PNG',
    tags: ['Angular', 'SASS'],
    source: 'https://github.com/RafaelRamirez21/Angular-video-game',
    visit: 'https://angular-game-rrrb.netlify.app/',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey in at University and code', },
  { year: 2018, text: 'I discovered python and started program code snippets', },
  { year: 2020, text: 'I programmed a genetic algorithms in python based on functional paradigms with a investigation team at the University.', },
  { year: 2021, text: 'Started  to make project as freelancer as web developer full stack', },
];